# Generated by Django 5.1.3 on 2024-11-27 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_subjects', to='home.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_subjects', to='home.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='ClassSubject',
        ),
    ]
