# Generated by Django 5.1.3 on 2024-12-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_studentenrollment_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('removed', 'Removed'), ('struck_off', 'Struck Off'), ('expelled', 'Expelled')], default='active', max_length=10),
        ),
    ]
